"""Evidence-backed recurring obligations and cancellation attempts.

Revision ID: 0023_recurring_obligations
Revises: 0022_plan_sources
"""

import sqlalchemy as sa
from alembic import op

revision = "0023_recurring_obligations"
down_revision = "0022_plan_sources"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=256), nullable=False),
        sa.Column("normalized_name", sa.String(length=256), nullable=False),
        sa.Column("website_domain", sa.String(length=256), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "user_id", "normalized_name", name="uq_merchant_owner_name"
        ),
    )
    op.create_index(op.f("ix_merchants_user_id"), "merchants", ["user_id"], unique=False)
    op.create_index(op.f("ix_merchants_workspace_id"), "merchants", ["workspace_id"], unique=False)
    op.create_table(
        "merchant_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=512), nullable=False),
        sa.Column("alias_type", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "user_id", "alias", "alias_type", name="uq_merchant_alias_owner"
        ),
    )
    op.create_index(
        op.f("ix_merchant_aliases_merchant_id"), "merchant_aliases", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_merchant_aliases_user_id"), "merchant_aliases", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_merchant_aliases_workspace_id"), "merchant_aliases", ["workspace_id"], unique=False
    )
    op.create_table(
        "recurring_obligations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("obligation_type", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("plan_name", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("billing_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("billing_currency", sa.String(length=3), nullable=True),
        sa.Column("billing_interval", sa.String(length=16), nullable=False),
        sa.Column("interval_count", sa.Integer(), nullable=False),
        sa.Column("next_renewal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trial_conversion_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("trial_conversion_interval", sa.String(length=16), nullable=True),
        sa.Column("trial_conversion_interval_count", sa.Integer(), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("review_state", sa.String(length=32), nullable=False),
        sa.Column("kept_cycle_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("review_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_identity", sa.String(length=512), nullable=True),
        sa.Column("cancellation_connection_id", sa.Uuid(), nullable=True),
        sa.Column("cancellation_external_resource_id", sa.String(length=512), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cancellation_connection_id"], ["connections.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recurring_obligations_cancellation_connection_id"),
        "recurring_obligations",
        ["cancellation_connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_obligations_merchant_id"),
        "recurring_obligations",
        ["merchant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_obligations_next_renewal_at"),
        "recurring_obligations",
        ["next_renewal_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_obligations_source_identity"),
        "recurring_obligations",
        ["source_identity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_obligations_status"), "recurring_obligations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_recurring_obligations_trial_ends_at"),
        "recurring_obligations",
        ["trial_ends_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_obligations_user_id"), "recurring_obligations", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_recurring_obligations_workspace_id"),
        "recurring_obligations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "recurring_obligation_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("obligation_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=40), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=True),
        sa.Column("external_resource_id", sa.String(length=512), nullable=True),
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column("merchant_text", sa.String(length=256), nullable=True),
        sa.Column("plan_text", sa.String(length=256), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("billing_interval", sa.String(length=16), nullable=True),
        sa.Column("interval_count", sa.Integer(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("renewal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["connection_id"], ["connections.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["obligation_id"], ["recurring_obligations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "user_id", "dedupe_key", name="uq_obligation_evidence_owner_dedupe"
        ),
    )
    op.create_index(
        op.f("ix_recurring_obligation_evidence_connection_id"),
        "recurring_obligation_evidence",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_obligation_evidence_obligation_id"),
        "recurring_obligation_evidence",
        ["obligation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_obligation_evidence_user_id"),
        "recurring_obligation_evidence",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_obligation_evidence_workspace_id"),
        "recurring_obligation_evidence",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "subscription_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("obligation_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("commitment_id", sa.Uuid(), nullable=True),
        sa.Column("delivery_state", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["commitment_id"], ["commitments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["obligation_id"], ["recurring_obligations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "user_id", "dedupe_key", name="uq_subscription_event_owner_dedupe"
        ),
    )
    op.create_index(
        op.f("ix_subscription_events_commitment_id"),
        "subscription_events",
        ["commitment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_events_delivery_state"),
        "subscription_events",
        ["delivery_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_events_obligation_id"),
        "subscription_events",
        ["obligation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_events_user_id"), "subscription_events", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscription_events_workspace_id"),
        "subscription_events",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "obligation_price_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("obligation_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("billing_interval", sa.String(length=16), nullable=False),
        sa.Column("interval_count", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["recurring_obligation_evidence.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["obligation_id"], ["recurring_obligations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_obligation_price_history_evidence_id"),
        "obligation_price_history",
        ["evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_obligation_price_history_obligation_id"),
        "obligation_price_history",
        ["obligation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_obligation_price_history_user_id"),
        "obligation_price_history",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_obligation_price_history_workspace_id"),
        "obligation_price_history",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "cancellation_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("obligation_id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("action_id", sa.Uuid(), nullable=True),
        sa.Column("approval_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("preview", sa.JSON(), nullable=False),
        sa.Column("provider_state_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("obligation_revision", sa.Integer(), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["action_id"], ["actions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["approval_id"], ["approvals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["obligation_id"], ["recurring_obligations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "user_id", "request_id", name="uq_cancellation_owner_request"
        ),
    )
    op.create_index(
        op.f("ix_cancellation_attempts_action_id"),
        "cancellation_attempts",
        ["action_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cancellation_attempts_approval_id"),
        "cancellation_attempts",
        ["approval_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cancellation_attempts_obligation_id"),
        "cancellation_attempts",
        ["obligation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cancellation_attempts_status"), "cancellation_attempts", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_cancellation_attempts_user_id"), "cancellation_attempts", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_cancellation_attempts_workspace_id"),
        "cancellation_attempts",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "cancellation_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("cancellation_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=40), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=True),
        sa.Column("external_resource_id", sa.String(length=512), nullable=True),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cancellation_attempt_id"], ["cancellation_attempts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["connection_id"], ["connections.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cancellation_evidence_cancellation_attempt_id"),
        "cancellation_evidence",
        ["cancellation_attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cancellation_evidence_connection_id"),
        "cancellation_evidence",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cancellation_evidence_user_id"), "cancellation_evidence", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_cancellation_evidence_workspace_id"),
        "cancellation_evidence",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cancellation_evidence_workspace_id"), table_name="cancellation_evidence")
    op.drop_index(op.f("ix_cancellation_evidence_user_id"), table_name="cancellation_evidence")
    op.drop_index(
        op.f("ix_cancellation_evidence_connection_id"), table_name="cancellation_evidence"
    )
    op.drop_index(
        op.f("ix_cancellation_evidence_cancellation_attempt_id"), table_name="cancellation_evidence"
    )
    op.drop_table("cancellation_evidence")
    op.drop_index(op.f("ix_cancellation_attempts_workspace_id"), table_name="cancellation_attempts")
    op.drop_index(op.f("ix_cancellation_attempts_user_id"), table_name="cancellation_attempts")
    op.drop_index(op.f("ix_cancellation_attempts_status"), table_name="cancellation_attempts")
    op.drop_index(
        op.f("ix_cancellation_attempts_obligation_id"), table_name="cancellation_attempts"
    )
    op.drop_index(op.f("ix_cancellation_attempts_approval_id"), table_name="cancellation_attempts")
    op.drop_index(op.f("ix_cancellation_attempts_action_id"), table_name="cancellation_attempts")
    op.drop_table("cancellation_attempts")
    op.drop_index(
        op.f("ix_obligation_price_history_workspace_id"), table_name="obligation_price_history"
    )
    op.drop_index(
        op.f("ix_obligation_price_history_user_id"), table_name="obligation_price_history"
    )
    op.drop_index(
        op.f("ix_obligation_price_history_obligation_id"), table_name="obligation_price_history"
    )
    op.drop_index(
        op.f("ix_obligation_price_history_evidence_id"), table_name="obligation_price_history"
    )
    op.drop_table("obligation_price_history")
    op.drop_index(op.f("ix_subscription_events_workspace_id"), table_name="subscription_events")
    op.drop_index(op.f("ix_subscription_events_user_id"), table_name="subscription_events")
    op.drop_index(op.f("ix_subscription_events_obligation_id"), table_name="subscription_events")
    op.drop_index(op.f("ix_subscription_events_delivery_state"), table_name="subscription_events")
    op.drop_index(op.f("ix_subscription_events_commitment_id"), table_name="subscription_events")
    op.drop_table("subscription_events")
    op.drop_index(
        op.f("ix_recurring_obligation_evidence_workspace_id"),
        table_name="recurring_obligation_evidence",
    )
    op.drop_index(
        op.f("ix_recurring_obligation_evidence_user_id"), table_name="recurring_obligation_evidence"
    )
    op.drop_index(
        op.f("ix_recurring_obligation_evidence_obligation_id"),
        table_name="recurring_obligation_evidence",
    )
    op.drop_index(
        op.f("ix_recurring_obligation_evidence_connection_id"),
        table_name="recurring_obligation_evidence",
    )
    op.drop_table("recurring_obligation_evidence")
    op.drop_index(op.f("ix_recurring_obligations_workspace_id"), table_name="recurring_obligations")
    op.drop_index(op.f("ix_recurring_obligations_user_id"), table_name="recurring_obligations")
    op.drop_index(
        op.f("ix_recurring_obligations_trial_ends_at"), table_name="recurring_obligations"
    )
    op.drop_index(op.f("ix_recurring_obligations_status"), table_name="recurring_obligations")
    op.drop_index(
        op.f("ix_recurring_obligations_source_identity"), table_name="recurring_obligations"
    )
    op.drop_index(
        op.f("ix_recurring_obligations_next_renewal_at"), table_name="recurring_obligations"
    )
    op.drop_index(op.f("ix_recurring_obligations_merchant_id"), table_name="recurring_obligations")
    op.drop_index(
        op.f("ix_recurring_obligations_cancellation_connection_id"),
        table_name="recurring_obligations",
    )
    op.drop_table("recurring_obligations")
    op.drop_index(op.f("ix_merchant_aliases_workspace_id"), table_name="merchant_aliases")
    op.drop_index(op.f("ix_merchant_aliases_user_id"), table_name="merchant_aliases")
    op.drop_index(op.f("ix_merchant_aliases_merchant_id"), table_name="merchant_aliases")
    op.drop_table("merchant_aliases")
    op.drop_index(op.f("ix_merchants_workspace_id"), table_name="merchants")
    op.drop_index(op.f("ix_merchants_user_id"), table_name="merchants")
    op.drop_table("merchants")
    # ### end Alembic commands ###
