"""Versioned AI registry and runtime evidence. No models or traffic are enabled."""

import sqlalchemy as sa
from alembic import op

revision = "0024_ai_registry"
down_revision = "0023_recurring_obligations"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_profiles",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("weights", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_prompts",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("name", "version"),
    )
    op.create_table(
        "ai_providers",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_registry_revisions",
        sa.Column("revision", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("snapshot", sa.Text(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("revision"),
    )
    op.create_table(
        "ai_registry_state",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_schemas",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("name", "version"),
    )
    op.create_table(
        "ai_models",
        sa.Column("id", sa.String(length=180), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider"],
            ["ai_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_routing_policies",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("scope_key", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("policy", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workspace_id", "scope_key"),
    )
    op.create_table(
        "ai_task_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("registry_revision", sa.Integer(), nullable=True),
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("profile", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("prompt", sa.String(length=170), nullable=False),
        sa.Column("schema", sa.String(length=170), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("reserved_cost", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("fallback_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("shadow", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_task_runs_workspace_id"), "ai_task_runs", ["workspace_id"], unique=False
    )
    op.create_index(op.f("ix_ai_task_runs_trace_id"), "ai_task_runs", ["trace_id"], unique=False)
    op.create_index(op.f("ix_ai_task_runs_task_id"), "ai_task_runs", ["task_id"], unique=False)
    op.create_index(op.f("ix_ai_task_runs_user_id"), "ai_task_runs", ["user_id"], unique=False)
    op.create_table(
        "ai_evaluation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.String(length=180), nullable=False),
        sa.Column("model_digest", sa.String(length=64), nullable=False),
        sa.Column("registry_revision", sa.Integer(), nullable=False),
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("prompt", sa.String(length=180), nullable=False),
        sa.Column("schema", sa.String(length=180), nullable=False),
        sa.Column("profile", sa.String(length=64), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["ai_models.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile"], ["ai_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["registry_revision"], ["ai_registry_revisions.revision"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_evaluation_runs_model_id"), "ai_evaluation_runs", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_evaluation_runs_profile"), "ai_evaluation_runs", ["profile"], unique=False
    )
    op.create_table(
        "ai_model_capabilities",
        sa.Column("model_id", sa.String(length=180), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["ai_models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("model_id", "capability"),
    )
    op.create_table(
        "ai_profile_assignments",
        sa.Column("profile", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=180), nullable=False),
        sa.Column("rollout_percent", sa.Integer(), nullable=False),
        sa.Column("shadow_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["ai_models.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile"], ["ai_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile", "model_id"),
    )
    op.create_table(
        "ai_provider_health",
        sa.Column("model_id", sa.String(length=180), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("retry_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("probe_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["model_id"], ["ai_models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("model_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_provider_health")
    op.drop_table("ai_profile_assignments")
    op.drop_table("ai_model_capabilities")
    op.drop_index(op.f("ix_ai_evaluation_runs_model_id"), table_name="ai_evaluation_runs")
    op.drop_index(op.f("ix_ai_evaluation_runs_profile"), table_name="ai_evaluation_runs")
    op.drop_table("ai_evaluation_runs")
    op.drop_index(op.f("ix_ai_task_runs_workspace_id"), table_name="ai_task_runs")
    op.drop_index(op.f("ix_ai_task_runs_trace_id"), table_name="ai_task_runs")
    op.drop_index(op.f("ix_ai_task_runs_task_id"), table_name="ai_task_runs")
    op.drop_index(op.f("ix_ai_task_runs_user_id"), table_name="ai_task_runs")
    op.drop_table("ai_task_runs")
    op.drop_table("ai_routing_policies")
    op.drop_table("ai_models")
    op.drop_table("ai_schemas")
    op.drop_table("ai_registry_state")
    op.drop_table("ai_registry_revisions")
    op.drop_table("ai_providers")
    op.drop_table("ai_prompts")
    op.drop_table("ai_profiles")
    # ### end Alembic commands ###
