"""Versioned draft approvals and NavoX-owned assistant session references."""

import sqlalchemy as sa
from alembic import op

revision = "0025_ai_drafts_sessions"
down_revision = "0024_ai_registry"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("next_sequence", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assistant_sessions_workspace_id"),
        "assistant_sessions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "assistant_turns",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("user_input_reference", sa.String(length=512), nullable=False),
        sa.Column("context_snapshot_reference", sa.String(length=512), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("output_reference", sa.String(length=512), nullable=False),
        sa.Column("action_refs", sa.JSON(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["assistant_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id", "sequence"),
        sa.UniqueConstraint("session_id", "task_id", name="uq_assistant_turn_task"),
    )
    op.create_table(
        "communication_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("commitment_id", sa.Uuid(), nullable=False),
        sa.Column("source_connection_id", sa.Uuid(), nullable=True),
        sa.Column("source_reference", sa.String(length=512), nullable=True),
        sa.Column("action_id", sa.Uuid(), nullable=True),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("approved_version", sa.Integer(), nullable=True),
        sa.Column("approved_payload_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["action_id"], ["actions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["commitment_id"], ["commitments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_connection_id"], ["connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_id"),
    )
    op.create_index(
        op.f("ix_communication_drafts_source_connection_id"),
        "communication_drafts",
        ["source_connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_communication_drafts_workspace_id"),
        "communication_drafts",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "communication_draft_versions",
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("generated_provider", sa.String(length=32), nullable=True),
        sa.Column("generated_model", sa.String(length=128), nullable=True),
        sa.Column("to", sa.JSON(), nullable=False),
        sa.Column("cc", sa.JSON(), nullable=False),
        sa.Column("bcc", sa.JSON(), nullable=False),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("attachment_refs", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=8), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["draft_id"], ["communication_drafts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("draft_id", "version"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("communication_draft_versions")
    op.drop_index(
        op.f("ix_communication_drafts_source_connection_id"), table_name="communication_drafts"
    )
    op.drop_index(op.f("ix_communication_drafts_workspace_id"), table_name="communication_drafts")
    op.drop_table("communication_drafts")
    op.drop_table("assistant_turns")
    op.drop_index(op.f("ix_assistant_sessions_workspace_id"), table_name="assistant_sessions")
    op.drop_table("assistant_sessions")
    # ### end Alembic commands ###
