"""News sources, rights, evidence, stories and private conversations."""

import sqlalchemy as sa
from alembic import op

revision = "0026_news_foundation"
down_revision = "0025_ai_drafts_sessions"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_preferences",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("entities", sa.JSON(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("reading_history_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "user_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("workspace_id", "user_id"),
    )
    op.create_table(
        "news_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("identity_verified", sa.Boolean(), nullable=False),
        sa.Column("independence_group", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("config_digest", sa.String(length=64), nullable=False),
        sa.Column("rights_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "user_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", "user_id", name="uq_news_source_scope"),
        sa.UniqueConstraint(
            "workspace_id", "user_id", "source_key", name="uq_news_source_owner_key"
        ),
    )
    op.create_index(
        op.f("ix_news_sources_workspace_id"), "news_sources", ["workspace_id"], unique=False
    )
    op.create_table(
        "news_content_rights",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("policy", sa.JSON(), nullable=False),
        sa.Column("policy_digest", sa.String(length=64), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["news_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "source_id", name="uq_news_rights_source_binding"),
        sa.UniqueConstraint("source_id", "version", name="uq_news_rights_source_version"),
    )
    op.create_table(
        "news_ingestion_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stored_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["news_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "request_id", name="uq_news_ingestion_request"),
    )
    op.create_table(
        "news_source_feeds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("feed_type", sa.String(length=32), nullable=False),
        sa.Column("endpoint_reference", sa.String(length=2048), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("poll_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("health_status", sa.String(length=32), nullable=False),
        sa.Column("last_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["news_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_table(
        "news_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("rights_profile_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=512), nullable=False),
        sa.Column("headline", sa.String(length=500), nullable=False),
        sa.Column("canonical_url", sa.String(length=2048), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rights_profile_id", "source_id"],
            ["news_content_rights.id", "news_content_rights.source_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id", "workspace_id", "user_id"],
            ["news_sources.id", "news_sources.workspace_id", "news_sources.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "source_id", name="uq_news_item_source"),
        sa.UniqueConstraint("id", "workspace_id", "user_id", name="uq_news_item_scope"),
        sa.UniqueConstraint("source_id", "external_id", name="uq_news_item_external"),
    )
    op.create_index(op.f("ix_news_items_expires_at"), "news_items", ["expires_at"], unique=False)
    op.create_index(op.f("ix_news_items_source_id"), "news_items", ["source_id"], unique=False)
    op.create_index(
        op.f("ix_news_items_workspace_id"), "news_items", ["workspace_id"], unique=False
    )
    op.create_table(
        "news_story_clusters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("anchor_item_id", sa.Uuid(), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=32), nullable=False),
        sa.Column("primary_category", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("suppressed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["anchor_item_id", "workspace_id", "user_id"],
            ["news_items.id", "news_items.workspace_id", "news_items.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("anchor_item_id"),
        sa.UniqueConstraint("id", "workspace_id", "user_id", name="uq_news_story_scope"),
    )
    op.create_index(
        op.f("ix_news_story_clusters_last_updated_at"),
        "news_story_clusters",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_story_clusters_workspace_id"),
        "news_story_clusters",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "news_claims",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("origin_item_id", sa.Uuid(), nullable=False),
        sa.Column("origin_revision", sa.Integer(), nullable=False),
        sa.Column("claim_text", sa.String(length=2000), nullable=False),
        sa.Column("text_digest", sa.String(length=64), nullable=False),
        sa.Column("claim_type", sa.String(length=64), nullable=False),
        sa.Column("attributed_to", sa.String(length=200), nullable=True),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id", "workspace_id", "user_id"],
            [
                "news_story_clusters.id",
                "news_story_clusters.workspace_id",
                "news_story_clusters.user_id",
            ],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["origin_item_id", "workspace_id", "user_id"],
            ["news_items.id", "news_items.workspace_id", "news_items.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cluster_id", "origin_item_id", "text_digest", name="uq_news_claim_origin"
        ),
        sa.UniqueConstraint("id", "workspace_id", "user_id", name="uq_news_claim_scope"),
    )
    op.create_index(op.f("ix_news_claims_cluster_id"), "news_claims", ["cluster_id"], unique=False)
    op.create_table(
        "news_conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("story_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["story_id", "workspace_id", "user_id"],
            [
                "news_story_clusters.id",
                "news_story_clusters.workspace_id",
                "news_story_clusters.user_id",
            ],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "user_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_news_conversations_expires_at"), "news_conversations", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_news_conversations_workspace_id"),
        "news_conversations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "news_story_items",
        sa.Column("news_item_id", sa.Uuid(), nullable=False),
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("item_revision", sa.Integer(), nullable=False),
        sa.Column("url_digest", sa.String(length=64), nullable=False),
        sa.Column("copy_digest", sa.String(length=64), nullable=True),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id", "workspace_id", "user_id"],
            [
                "news_story_clusters.id",
                "news_story_clusters.workspace_id",
                "news_story_clusters.user_id",
            ],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["news_item_id", "workspace_id", "user_id"],
            ["news_items.id", "news_items.workspace_id", "news_items.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("news_item_id"),
    )
    op.create_index(
        op.f("ix_news_story_items_cluster_id"), "news_story_items", ["cluster_id"], unique=False
    )
    op.create_index(
        op.f("ix_news_story_items_copy_digest"), "news_story_items", ["copy_digest"], unique=False
    )
    op.create_index(
        op.f("ix_news_story_items_url_digest"), "news_story_items", ["url_digest"], unique=False
    )
    op.create_table(
        "news_story_preferences",
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("saved", sa.Boolean(), nullable=False),
        sa.Column("dismissed", sa.Boolean(), nullable=False),
        sa.Column("followed", sa.Boolean(), nullable=False),
        sa.Column("last_read_version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id", "workspace_id", "user_id"],
            [
                "news_story_clusters.id",
                "news_story_clusters.workspace_id",
                "news_story_clusters.user_id",
            ],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("cluster_id"),
    )
    op.create_table(
        "news_story_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("change_kind", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot", sa.JSON(), nullable=False),
        sa.Column("claim_states", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cluster_id"], ["news_story_clusters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cluster_id", "version", name="uq_news_story_version"),
    )
    op.create_table(
        "news_claim_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("news_item_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("item_revision", sa.Integer(), nullable=False),
        sa.Column("quote_field", sa.String(length=32), nullable=False),
        sa.Column("quote_start", sa.Integer(), nullable=False),
        sa.Column("quote_end", sa.Integer(), nullable=False),
        sa.Column("relationship", sa.String(length=32), nullable=False),
        sa.Column("evidence_kind", sa.String(length=32), nullable=False),
        sa.Column("evidence_strength", sa.String(length=32), nullable=False),
        sa.Column("provenance_group", sa.String(length=128), nullable=False),
        sa.Column("independence_group", sa.String(length=128), nullable=False),
        sa.Column("origin_groups", sa.JSON(), nullable=False),
        sa.Column("review_reference", sa.String(length=128), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id", "workspace_id", "user_id"],
            ["news_claims.id", "news_claims.workspace_id", "news_claims.user_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["news_item_id", "source_id"],
            ["news_items.id", "news_items.source_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["news_item_id", "workspace_id", "user_id"],
            ["news_items.id", "news_items.workspace_id", "news_items.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("claim_id", "news_item_id", name="uq_news_evidence_claim_item"),
    )
    op.create_index(
        op.f("ix_news_claim_evidence_claim_id"), "news_claim_evidence", ["claim_id"], unique=False
    )
    op.create_index(
        op.f("ix_news_claim_evidence_news_item_id"),
        "news_claim_evidence",
        ["news_item_id"],
        unique=False,
    )
    op.create_table(
        "news_conversation_turns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(length=2000), nullable=False),
        sa.Column("intent", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("selection", sa.JSON(), nullable=True),
        sa.Column("source_snapshot", sa.JSON(), nullable=False),
        sa.Column("context_digest", sa.String(length=64), nullable=True),
        sa.Column("trace_id", sa.Uuid(), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["news_conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "request_id", name="uq_news_turn_request"),
        sa.UniqueConstraint("conversation_id", "sequence", name="uq_news_turn_sequence"),
    )
    op.create_index(
        op.f("ix_news_conversation_turns_conversation_id"),
        "news_conversation_turns",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_conversation_turns_expires_at"),
        "news_conversation_turns",
        ["expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_news_conversation_turns_expires_at"), table_name="news_conversation_turns"
    )
    op.drop_index(
        op.f("ix_news_conversation_turns_conversation_id"), table_name="news_conversation_turns"
    )
    op.drop_table("news_conversation_turns")
    op.drop_index(op.f("ix_news_claim_evidence_news_item_id"), table_name="news_claim_evidence")
    op.drop_index(op.f("ix_news_claim_evidence_claim_id"), table_name="news_claim_evidence")
    op.drop_table("news_claim_evidence")
    op.drop_table("news_story_versions")
    op.drop_table("news_story_preferences")
    op.drop_index(op.f("ix_news_story_items_url_digest"), table_name="news_story_items")
    op.drop_index(op.f("ix_news_story_items_copy_digest"), table_name="news_story_items")
    op.drop_index(op.f("ix_news_story_items_cluster_id"), table_name="news_story_items")
    op.drop_table("news_story_items")
    op.drop_index(op.f("ix_news_conversations_workspace_id"), table_name="news_conversations")
    op.drop_index(op.f("ix_news_conversations_expires_at"), table_name="news_conversations")
    op.drop_table("news_conversations")
    op.drop_index(op.f("ix_news_claims_cluster_id"), table_name="news_claims")
    op.drop_table("news_claims")
    op.drop_index(op.f("ix_news_story_clusters_workspace_id"), table_name="news_story_clusters")
    op.drop_index(op.f("ix_news_story_clusters_last_updated_at"), table_name="news_story_clusters")
    op.drop_table("news_story_clusters")
    op.drop_index(op.f("ix_news_items_workspace_id"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_source_id"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_expires_at"), table_name="news_items")
    op.drop_table("news_items")
    op.drop_table("news_source_feeds")
    op.drop_table("news_ingestion_receipts")
    op.drop_table("news_content_rights")
    op.drop_index(op.f("ix_news_sources_workspace_id"), table_name="news_sources")
    op.drop_table("news_sources")
    op.drop_table("news_preferences")
    # ### end Alembic commands ###
